baseURL = "https://amtsimplified.com/"
languageCode = "en-us"
title = "AMT Simplified"
theme = "minimal"
googleAnalytics = "UA-171252878-1"

[params]
    author = "Dion Wu"
    description = "Helping you understand, calculate, and plan for your Alternative Minimum Tax (AMT)"
    home_subtitle_1 = "Helping you understand, calculate, and plan for your"
    home_subtitle_2 = "Alternative Minimum Tax (AMT)"
    githubUsername = "#"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Montserrat" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    gtm_id = "GTM-KZWZW7N"
    gtm_datalayer = "basic"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/learn_about_the_amt/"
    name = "Learn about the AMT"
    weight = 2

[[menu.main]]
    url = "/tax_credits_deductions/"
    name = "Tax Credits & Deductions"
    weight = 3

[[menu.main]]
    url = "/amt-calculator/"
    name = "AMT Calculator"
    weight = 4

[[menu.main]]
    url = "/iso-exercise-planner/"
    name = "Incentive Stock Option Tax Planner"
    weight = 5

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 6

[[menu.main]]
    url = "https://www.buymeacoffee.com/amtsimplified"
    name = "Support Me!"
    weight = 7    

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:amtsimplified@gmail.com"
    name = "envelope-o"
    weight = 1

#[[menu.icon]]
    #url = "https://twitter.com/username/"
    #name = "twitter"
    #weight = 3

#[[menu.icon]]
    #url = "https://www.linkedin.com/in/username/"
    #name = "linkedin"
    #weight = 4

#[[menu.icon]]
    #url = "https://www.stackoverflow.com/username/"
    #name = "stack-overflow"
    #weight = 5ß
